@echo off
chcp 65001 >nul
echo 🔧 DANG SUA LOI HE THONG (ChunkLoadError)...
echo 1. Dung toan bo tien trinh Node.js...
taskkill /F /IM node.exe >nul 2>&1

echo 2. Xoa cache Webpack (Fix loi xoay vong)...
if exist .next rd /s /q .next

echo 3. Khoi dong lai Server...
echo Vui long cho trong giay lat...
call START_APP.bat
