export interface QuestDefinition {
  id: string;
  category: 'attendance_discipline' | 'academic_progress' | 'teamwork_activities' | 'family_lifeskills';
  categoryName: string;
  categoryIcon: string;
  title: string;
  description: string;
  hint: string;
  xpReward: number;
  coinReward: number;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const QUEST_BANK: QuestDefinition[] = [
  // =========================================================================
  // NHÓM 1: CHUYÊN CẦN & NỀ NẾP KỶ LUẬT (20 NHIỆM VỤ)
  // =========================================================================
  {
    id: 'att_01',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '⏰',
    title: 'Chiến Binh Đúng Giờ',
    description: 'Có mặt tại lớp học trước giờ truy bài ít nhất 10 phút trong 5 ngày liên tiếp.',
    hint: 'Ghi lại khung giờ đến lớp mỗi ngày hoặc nhờ sao đỏ/lớp trưởng xác nhận.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_02',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '👔',
    title: 'Đồng Phục Chuẩn Mực',
    description: 'Mặc đồng phục đúng quy định, đeo khăn quàng và bảng tên đầy đủ suốt tuần.',
    hint: 'Chụp ảnh góc học tập hoặc bảng kiểm tra thi đua tuần.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_03',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '📖',
    title: '15 Phút Truy Bài Nghiêm Túc',
    description: 'Ngồi ngay ngắn, ôn tập bài cũ cùng tổ trưởng trong 15 phút đầu giờ suốt cả tuần.',
    hint: 'Ghi chép 3 câu hỏi bài cũ đã ôn luyện trong sổ tay.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'att_04',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '📱',
    title: 'Giờ Học Không Điện Thoại',
    description: 'Tuyệt đối không sử dụng thiết bị điện tử trong giờ học khi chưa có yêu cầu của thầy cô.',
    hint: 'Tự giác cất điện thoại vào ngăn bàn/tủ đồ chung của lớp.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_05',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🧹',
    title: 'Bàn Học Gọn Gàng',
    description: 'Giữ hộc bàn và khu vực ngồi xung quanh sạch sẽ, không có rác thải sau mỗi buổi học.',
    hint: 'Chụp ảnh hộc bàn trước khi ra về vào cuối buổi học thứ 6.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_06',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🎒',
    title: 'Soạn Cặp Theo Thời Khóa Biểu',
    description: 'Tự giác chuẩn bị đầy đủ sách vở và dụng cụ học tập trước 10h tối mỗi ngày.',
    hint: 'Liệt kê danh sách đồ dùng môn học đã chuẩn bị cho ngày mai.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_07',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🤫',
    title: 'Tôn Trọng Trật Tự Tiết Tự Quản',
    description: 'Tự học nghiêm túc khi giáo viên bộ môn vắng mặt hoặc trong các tiết tự học.',
    hint: 'Ghi lại bài tập hoặc phần lý thuyết đã tự nghiên cứu trong tiết.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'att_08',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🙋',
    title: 'Phát Biểu Có Kỷ Luật',
    description: 'Giơ tay phát biểu ý kiến đúng nghi thức và lắng nghe khi bạn khác đang trình bày.',
    hint: 'Ghi lại 2 lần phát biểu đóng góp bài trên lớp.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_09',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '💡',
    title: 'Tắt Điện Khi Rời Phòng',
    description: 'Chủ động tắt đèn, quạt và điều hòa khi lớp di chuyển ra sân thể dục hoặc phòng lab.',
    hint: 'Chụp ảnh công tắc đã ngắt hoặc nhờ sao đỏ xác nhận.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_10',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🛡️',
    title: 'Bảo Vệ Bàn Ghế Cơ Sở Vật Chất',
    description: 'Không vẽ bậy lên bàn ghế, lau sạch các vết bẩn vô ý trên mặt bàn lớp học.',
    hint: 'Chụp ảnh góc bàn sạch sẽ không có vết mực bậy.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_11',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🏃',
    title: 'Hàng Ngũ Tập Thể Dục Thẳng Tắp',
    description: 'Xếp hàng nhanh chóng và tập bài thể dục giữa giờ đúng nhịp điệu quy định.',
    hint: 'Nhờ tổ trưởng ghi nhận tinh thần tập luyện tích cực.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_12',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🤝',
    title: 'Chào Hỏi Thầy Cô & Khách Đến Lớp',
    description: 'Đứng dậy ngay ngắn chào thầy cô khi vào/ra lớp và lịch sự với khách đến thăm trường.',
    hint: 'Ghi lại cảm nhận về sự lễ phép và tôn sư trọng đạo.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_13',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '📝',
    title: 'Ghi Chép Sổ Đầu Bài Đầy Đủ',
    description: 'Hỗ trợ ban cán sự lớp bảo quản và giữ gìn sổ theo dõi nề nếp cẩn thận.',
    hint: 'Xác nhận hoàn thành các cột mục nề nếp trong tuần.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'att_14',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🚶',
    title: 'Di Chuyển Giữ Khoảng Cách An Toàn',
    description: 'Đi lại nhẹ nhàng trong hành lang, không xô đẩy hay chạy nhảy nguy hiểm.',
    hint: 'Ghi lại lời cam kết an toàn học đường cùng nhóm bạn.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_15',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🗑️',
    title: 'Phân Loại Rác Lớp Học',
    description: 'Bỏ rác đúng nơi quy định, phân biệt rác tái chế (giấy vụn) và rác sinh hoạt.',
    hint: 'Gom giấy vụn vào thùng tái chế của lớp.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_16',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '📐',
    title: 'Đầy Đủ Dụng Cụ Học Tập',
    description: 'Mang đủ compa, thước kẻ, máy tính cầm tay và bút viết trong các tiết Toán & KHTN.',
    hint: 'Chụp ảnh hộp bút đầy đủ dụng cụ học tập.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_17',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🪑',
    title: 'Kê Ngay Ngắn Bàn Ghế Cuối Giờ',
    description: 'Cùng các bạn trong dãy kê lại bàn ghế thẳng hàng trước khi đóng cửa phòng học.',
    hint: 'Chụp ảnh hàng bàn ghế thẳng tắp cuối buổi học.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'att_18',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '⏰',
    title: 'Vào Lớp Đúng Tiếng Chuông',
    description: 'Nhanh chóng ổn định chỗ ngồi ngay khi có hiệu lệnh chuông báo vào tiết học.',
    hint: 'Không trễ tiết nào trong suốt 5 ngày học.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'att_19',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '📜',
    title: 'Bảo Quản Sách Giáo Khoa Bìa Bọc Đẹp',
    description: 'Bọc bìa và giữ gìn sách giáo khoa không bị quăn mép hay rách nát.',
    hint: 'Chụp ảnh bộ sách giáo khoa được dán nhãn tên và bọc bìa phẳng phiu.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'att_20',
    category: 'attendance_discipline',
    categoryName: 'Chuyên Cần & Nề Nếp',
    categoryIcon: '🏅',
    title: 'Tuần Lễ Kỷ Luật Vàng',
    description: 'Không vi phạm bất kỳ lỗi trừ điểm thi đua nào của lớp trong suốt cả tuần.',
    hint: 'Tổng kết điểm chuyên cần đạt 100% trong bảng sao đỏ.',
    xpReward: 50,
    coinReward: 30,
    difficulty: 'hard'
  },

  // =========================================================================
  // NHÓM 2: HỌC TẬP & TIẾN BỘ TRI THỨC (20 NHIỆM VỤ)
  // =========================================================================
  {
    id: 'aca_01',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🧠',
    title: 'Sơ Đồ Tư Duy 1 Chương Bài',
    description: 'Vẽ sơ đồ tư duy (Mindmap) tóm tắt nội dung của 1 chương môn Khoa học Tự nhiên hoặc Lịch sử & Địa lý.',
    hint: 'Chụp ảnh sơ đồ tư duy có tô màu phân nhánh rõ ràng.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'aca_02',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '📐',
    title: 'Chinh Phục 5 Bài Toán Nâng Cao',
    description: 'Giải hoàn chỉnh 5 bài tập toán hình học hoặc đại số dạng vận dụng nâng cao.',
    hint: 'Chụp ảnh bài giải chi tiết từng bước.',
    xpReward: 45,
    coinReward: 25,
    difficulty: 'hard'
  },
  {
    id: 'aca_03',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '📚',
    title: 'Đọc & Tóm Tắt 1 Cuốn Sách Hay',
    description: 'Đọc xong 1 cuốn sách khoa học/văn học và viết đoạn cảm nhận ngắn 150 chữ.',
    hint: 'Ghi lại tên sách, tác giả và 3 bài học tâm đắc nhất.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'aca_04',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🇬🇧',
    title: 'Học 20 Từ Vựng Tiếng Anh Mới',
    description: 'Ghi chép và đặt câu với 20 từ vựng tiếng Anh theo chủ đề đang học trên lớp.',
    hint: 'Chụp ảnh sổ tay từ vựng có kèm phiên âm và nghĩa.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'aca_05',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🧪',
    title: 'Mô Tả Thí Nghiệm Khoa Học',
    description: 'Quan sát hoặc thực hành một thí nghiệm Vật lý/Hóa học/Sinh học và ghi chép hiện tượng.',
    hint: 'Viết báo cáo ngắn: Dụng cụ, các bước tiến hành, kết quả quan sát.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'aca_06',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '✍️',
    title: 'Luyện Viết Đoạn Văn Nghị Luận',
    description: 'Viết một đoạn văn nghị luận xã hội về một đức tính tốt đẹp (lòng biết ơn, tính trung thực...).',
    hint: 'Đoạn văn từ 150 - 200 chữ có dẫn chứng cụ thể.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'aca_07',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '💻',
    title: 'Soạn Thảo Bài Thuyết Trình Tin Học',
    description: 'Tạo một bài trình chiếu PowerPoint gồm 5 trang về một chủ đề học tập yêu thích.',
    hint: 'Chụp ảnh màn hình các slide có bố cục đẹp và hình ảnh sinh động.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'aca_08',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '💯',
    title: 'Đạt Điểm Tốt Trong Giờ Học',
    description: 'Giành được ít nhất một điểm 9 hoặc 10 trong bài kiểm tra miệng hoặc kiểm tra 15 phút.',
    hint: 'Ghi lại môn học và lời nhận xét khen ngợi của giáo viên.',
    xpReward: 50,
    coinReward: 30,
    difficulty: 'hard'
  },
  {
    id: 'aca_09',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🎯',
    title: 'Hoàn Thành Bài Tập Về Nhà Sớm',
    description: 'Hoàn thành 100% bài tập về nhà của tất cả các môn trước 9h tối trong 3 ngày liên tiếp.',
    hint: 'Chụp ảnh chữ ký kiểm tra của phụ huynh hoặc sổ bài tập đầy đủ.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'aca_10',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🔍',
    title: 'Tìm Hiểu 1 Nhà Khoa Học Lỗi Lạc',
    description: 'Đọc tiểu sử của 1 nhà bác học (Newton, Einstein, Marie Curie...) và chia sẻ phát minh vĩ đại.',
    hint: 'Viết 5 câu tóm tắt về cuộc đời và đóng góp của nhà khoa học.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'aca_11',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🎙️',
    title: 'Luyện Phát Âm Đoạn Hội Thoại Ngoại Ngữ',
    description: 'Ghi âm hoặc tự luyện đọc trôi chảy 1 đoạn hội thoại tiếng Anh trong sách giáo khoa.',
    hint: 'Luyện tập ngữ điệu và phát âm chuẩn các âm đuôi.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'aca_12',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🗺️',
    title: 'Khám Phá Bản Đồ Địa Lý',
    description: 'Xác định trên bản đồ vị trí 5 thành phố lớn và các vùng kinh tế trọng điểm của Việt Nam.',
    hint: 'Vẽ hoặc tô màu lên bản đồ lược đồ địa lý.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'aca_13',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '📜',
    title: 'Ghi Nhớ Mốc Lịch Sử Quan Trọng',
    description: 'Lập bảng niên biểu 5 mốc sự kiện lịch sử quan trọng trong giai đoạn đang học.',
    hint: 'Bảng gồm 3 cột: Thời gian, Sự kiện, Ý nghĩa lịch sử.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'aca_14',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🔬',
    title: 'Quan Sát Thế Giới Tự Nhiên',
    description: 'Quan sát và ghi lại quá trình sinh trưởng của một loài thực vật hoặc tập tính của thú cưng.',
    hint: 'Ghi chép nhật ký quan sát trong 3 ngày.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'aca_15',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '💡',
    title: 'Đưa Ra Cách Giải Toán Mới',
    description: 'Tìm được ít nhất 2 cách giải khác nhau cho một bài toán hình học hoặc đại số.',
    hint: 'Trình bày rõ ràng Cách 1 và Cách 2 vào vở bài tập.',
    xpReward: 50,
    coinReward: 25,
    difficulty: 'hard'
  },
  {
    id: 'aca_16',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '📖',
    title: 'Đọc Báo Khăn Quàng Đỏ / Toán Tuổi Thơ',
    description: 'Đọc 1 bài viết hay trên báo Đội/Toán học và chia sẻ lại cho bạn cùng bàn.',
    hint: 'Ghi lại bài toán hoặc câu chuyện thú vị em vừa đọc.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'aca_17',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🧮',
    title: 'Rèn Luyện Tính Nhẩm Nhanh',
    description: 'Luyện tập 15 phép tính nhẩm nhân chia số có hai chữ số trong vòng 3 phút.',
    hint: 'Chụp lại bảng tính nhẩm và thời gian hoàn thành.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'aca_18',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '📝',
    title: 'Tự Soạn Câu Hỏi Trắc Nghiệm Ôn Tập',
    description: 'Tự biên soạn 5 câu hỏi trắc nghiệm 4 đáp án cho bài học vừa qua để đố bạn trong nhóm.',
    hint: 'Kèm theo đáp án đúng và giải thích ngắn gọn.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'aca_19',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🏆',
    title: 'Gia Sư Nhỏ Cho Bạn Cùng Bàn',
    description: 'Hướng dẫn bạn cùng bàn hiểu rõ một bài tập khó mà bạn chưa nắm vững.',
    hint: 'Nhờ bạn viết lời cảm ơn hoặc xác nhận đã hiểu bài.',
    xpReward: 45,
    coinReward: 25,
    difficulty: 'hard'
  },
  {
    id: 'aca_20',
    category: 'academic_progress',
    categoryName: 'Học Tập & Tri Thức',
    categoryIcon: '🌟',
    title: 'Bứt Phá Điểm Số Tuần',
    description: 'Cải thiện điểm số của một môn học còn yếu lên mức Khá/Giỏi trong tuần.',
    hint: 'Chụp điểm bài kiểm tra tiến bộ so với tuần trước.',
    xpReward: 50,
    coinReward: 30,
    difficulty: 'hard'
  },

  // =========================================================================
  // NHÓM 3: PHONG TRÀO ĐOÀN THỂ & PHỐI HỢP ĐỘI NHÓM (20 NHIỆM VỤ)
  // =========================================================================
  {
    id: 'team_01',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🧹',
    title: 'Trực Nhật Xuất Sắc',
    description: 'Lau bảng sạch bóng, quét dọn lớp học phẳng phiu và đổ rác đúng giờ quy định.',
    hint: 'Chụp ảnh lớp học sạch đẹp sau ca trực nhật.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'team_02',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🎨',
    title: 'Đóng Góp Báo Tường / Góc Học Tập',
    description: 'Vẽ 1 bức tranh hoặc viết 1 bài thơ ngắn đóng góp cho góc báo tường của lớp.',
    hint: 'Chụp tác phẩm đã được dán lên bảng tin lớp.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'team_03',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🤝',
    title: 'Đôi Bạn Cùng Tiến',
    description: 'Cùng người bạn thân học chung 1 buổi tối qua video call hoặc học nhóm tại thư viện.',
    hint: 'Chụp ảnh góc học tập chung hoặc sổ bài tập đôi.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'team_04',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🎵',
    title: 'Hát Vang Bài Ca Đội / Đoàn',
    description: 'Hát to, rõ ràng và thuộc trọn vẹn lời bài hát truyền thống trong giờ sinh hoạt.',
    hint: 'Thuộc lời Quốc ca, Đội ca hoặc bài hát chủ đề tháng.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'team_05',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🌿',
    title: 'Chăm Sóc Công Trình Măng Non',
    description: 'Tưới nước và nhặt lá vàng cho bồn hoa/cây xanh được phân công của lớp.',
    hint: 'Chụp ảnh bồn cây xanh tươi sau khi tưới nước.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'team_06',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '⚽',
    title: 'Tham Gia Hoạt Động Thể Thao Tập Thể',
    description: 'Chơi bóng đá, cầu lông, bóng rổ hoặc nhảy dây cùng các bạn trong giờ ra chơi.',
    hint: 'Ghi lại tinh thần đoàn kết và niềm vui sau trận đấu.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'team_07',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '💡',
    title: 'Đóng Góp Ý Tưởng Sáng Tạo Cho Lớp',
    description: 'Đề xuất 1 ý tưởng trò chơi hoặc giải pháp nâng cao thi đua trong giờ sinh hoạt lớp thứ 7.',
    hint: 'Ghi lại ý tưởng đã được thầy cô và lớp tán thành.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'team_08',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '📦',
    title: 'Kế Hoạch Nhỏ - Gom Giấy Vụn',
    description: 'Thu gom ít nhất 2kg giấy báo cũ/vỏ hộp sạch để ủng hộ phong trào Kế Hoạch Nhỏ.',
    hint: 'Chụp ảnh túi giấy vụn đã cân và nộp cho lớp phó phong trào.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'team_09',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '📚',
    title: 'Đóng Góp Tủ Sách Lớp Học',
    description: 'Mang 1 cuốn truyện/sách tham khảo hay đến góp vào tủ sách dùng chung của lớp.',
    hint: 'Dán nhãn tên và ghi vào sổ theo dõi mượn sách lớp.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'team_10',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🛡️',
    title: 'Nói Không Với Bạo Lực Học Đường',
    description: 'Xây dựng tinh thần đoàn kết, can ngăn hoặc báo thầy cô khi thấy bạn bè xích mích.',
    hint: 'Ghi lại thông điệp về tình bạn đẹp trong lớp.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'team_11',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🙋',
    title: 'Làm Người Dẫn Trò Giờ Sinh Hoạt',
    description: 'Phối hợp cùng quản ca hoặc ban cán sự tổ chức 1 mini-game vui nhộn 10 phút.',
    hint: 'Chuẩn bị câu hỏi và luật chơi ngắn gọn, dễ hiểu.',
    xpReward: 45,
    coinReward: 25,
    difficulty: 'hard'
  },
  {
    id: 'team_12',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🎁',
    title: 'Làm Thiệp Tặng Thầy Cô / Bạn Bè',
    description: 'Tự tay làm một tấm thiệp chúc mừng sinh nhật bạn hoặc tri ân thầy cô.',
    hint: 'Chụp ảnh tấm thiệp xinh xắn tự trang trí.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'team_13',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '👥',
    title: 'Họp Nhóm Học Tập Hiệu Quả',
    description: 'Chủ trì hoặc tham gia tích cực vào một buổi thảo luận nhóm phân công bài tập lớn.',
    hint: 'Ghi lại biên bản phân công công việc của các thành viên.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'team_14',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🥤',
    title: 'Giảm Thiểu Rác Thải Nhựa',
    description: 'Sử dụng bình nước cá nhân thay vì mua chai nhựa dùng một lần trong suốt tuần học.',
    hint: 'Chụp ảnh bình nước mang theo mỗi ngày.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'team_15',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🎭',
    title: 'Tham Gia Tiểu Phẩm Sinh Hoạt Dưới Cờ',
    description: 'Tập luyện và biểu diễn trong một tiết mục văn nghệ hoặc kịch tuyên truyền của trường.',
    hint: 'Ghi lại vai diễn hoặc chụp ảnh kỷ niệm cùng đội kịch.',
    xpReward: 50,
    coinReward: 30,
    difficulty: 'hard'
  },
  {
    id: 'team_16',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '📢',
    title: 'Đọc Phát Thanh Măng Non',
    description: 'Viết hoặc đọc bài tuyên truyền an toàn giao thông/bảo vệ môi trường trên loa trường.',
    hint: 'Ghi lại nội dung bài phát thanh đã phát sóng.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'team_17',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🌟',
    title: 'Gương Người Tốt Việc Tốt',
    description: 'Nhặt được của rơi trả lại người mất hoặc có hành động giúp đỡ người già, em nhỏ.',
    hint: 'Ghi lại việc tốt đã làm và cảm xúc vui vẻ của em.',
    xpReward: 45,
    coinReward: 25,
    difficulty: 'hard'
  },
  {
    id: 'team_18',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🏁',
    title: 'Cổ Vũ Nhiệt Tình Cho Đội Lớp',
    description: 'Có mặt cổ vũ hết mình và văn minh cho đội tuyển kéo co/bóng đá của lớp thi đấu.',
    hint: 'Chụp ảnh cùng các bạn cổ động viên mang cờ hoa.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'team_19',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🤝',
    title: 'Kết Thân Với Bạn Mới Chuyển Đến',
    description: 'Chủ động trò chuyện, giới thiệu khuôn viên trường cho bạn học sinh mới vào lớp.',
    hint: 'Ghi lại tên người bạn mới quen và chia sẻ cảm nghĩ.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'team_20',
    category: 'teamwork_activities',
    categoryName: 'Phong Trào & Đội Nhóm',
    categoryIcon: '🏆',
    title: 'Ngôi Sao Phong Trào Tuần',
    description: 'Được tập thể lớp bình chọn là cá nhân có đóng góp phong trào xuất sắc nhất tuần.',
    hint: 'Có tên trong bảng vinh danh tiết sinh hoạt lớp.',
    xpReward: 50,
    coinReward: 35,
    difficulty: 'hard'
  },

  // =========================================================================
  // NHÓM 4: GIA ĐÌNH & KỸ NĂNG SỐNG (20 NHIỆM VỤ)
  // =========================================================================
  {
    id: 'fam_01',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🍳',
    title: 'Đầu Bếp Nhí - Phụ Mẹ Nấu Cơm',
    description: 'Tự tay nhặt rau, cắm cơm hoặc nấu một món ăn đơn giản cho bữa cơm gia đình.',
    hint: 'Chụp ảnh mâm cơm ngon lành có món em tự nấu.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'fam_02',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🛏️',
    title: 'Gấp Chăn Màn Ngăn Nắp Mỗi Sáng',
    description: 'Thức dậy tự giác gấp chăn gối vuông vắn và dọn giường gọn gàng suốt 7 ngày.',
    hint: 'Chụp ảnh chiếc giường phẳng phiu vào buổi sáng.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_03',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🧺',
    title: 'Phơi & Gấp Quần Áo Gọn Gàng',
    description: 'Giúp bố mẹ phơi đồ và gấp gọn quần áo của bản thân vào tủ đồ cá nhân.',
    hint: 'Chụp ảnh ngăn tủ quần áo được sắp xếp ngăn nắp.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_04',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🏃',
    title: 'Rèn Luyện Thể Lực 30 Phút',
    description: 'Chạy bộ, đạp xe hoặc tập thể dục tại nhà liên tục 30 phút để nâng cao sức khỏe.',
    hint: 'Ghi lại thời gian tập luyện hoặc ảnh hoạt động thể thao.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_05',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '💧',
    title: 'Tiết Kiệm Điện Nước Gia Đình',
    description: 'Kiểm tra khóa vòi nước cẩn thận, tắt đèn phòng khi không sử dụng suốt tuần.',
    hint: 'Nhờ phụ huynh xác nhận tinh thần tiết kiệm năng lượng.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'fam_06',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🧼',
    title: 'Rửa Bát Đĩa Sạch Sẽ',
    description: 'Chủ động rửa và úp gọn gàng toàn bộ bát đĩa sau bữa tối của gia đình.',
    hint: 'Chụp ảnh kệ bát đĩa sạch bóng sau khi rửa.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'fam_07',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🚲',
    title: 'Tự Vệ Sinh & Bảo Dưỡng Xe Đạp',
    description: 'Lau chùi sạch sẽ xe đạp, tra dầu xích và bơm lốp xe sẵn sàng cho tuần học mới.',
    hint: 'Chụp ảnh chiếc xe đạp sáng bóng và an toàn.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_08',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '👵',
    title: 'Trò Chuyện & Đấm Lưng Cho Ông Bà',
    description: 'Dành 20 phút trò chuyện, hỏi thăm sức khỏe và đấm lưng thư giãn cho ông bà/cha mẹ.',
    hint: 'Viết cảm nghĩ về niềm vui của ông bà khi được quan tâm.',
    xpReward: 35,
    coinReward: 15,
    difficulty: 'medium'
  },
  {
    id: 'fam_09',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🪴',
    title: 'Chăm Sóc Cây Cảnh Ban Công',
    description: 'Tưới nước, bắt sâu và tỉa cành khô cho cây hoa/chậu cây cảnh tại gia đình.',
    hint: 'Chụp ảnh góc ban công/vườn nhà xanh mướt.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'fam_10',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '💰',
    title: 'Lập Kế Hoạch Quản Lý Chi Tiêu',
    description: 'Ghi chép nhật ký chi tiêu tiền tiêu vặt trong tuần và nuôi heo đất tiết kiệm.',
    hint: 'Chụp bảng ghi chép thu chi cá nhân đơn giản.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'fam_11',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🩹',
    title: 'Học Kỹ Năng Sơ Cứu Cơ Bản',
    description: 'Học và thực hành cách xử lý vết trầy xước, bỏng nhẹ hoặc băng bó ngón tay.',
    hint: 'Ghi lại 3 bước sơ cứu chuẩn khi bị trầy xước da.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'fam_12',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🔥',
    title: 'Kỹ Năng Thoát Hiểm Phòng Cháy Chữa Cháy',
    description: 'Tìm hiểu vị trí bình cứu hỏa trong tòa nhà/nhà ở và nắm vững đường thoát hiểm.',
    hint: 'Ghi lại số điện thoại cứu hỏa (114) và 3 kỹ năng thoát khói an toàn.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'fam_13',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🧹',
    title: 'Tổng Vệ Sinh Phòng Ngủ Cuối Tuần',
    description: 'Quét bụi, lau sàn và sắp xếp lại toàn bộ kệ sách, bàn học vào ngày Chủ Nhật.',
    hint: 'Chụp ảnh căn phòng sạch sẽ tinh tươm trước và sau khi dọn.',
    xpReward: 40,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'fam_14',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🐶',
    title: 'Chăm Sóc Thú Cưng Gia Đình',
    description: 'Cho chó/mèo ăn đúng giờ, dọn dẹp khay vệ sinh và chải lông cho thú cưng.',
    hint: 'Chụp ảnh cùng chú cún/mèo cưng khỏe mạnh.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_15',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🍎',
    title: 'Ăn Uống Lành Mạnh & Uống Đủ Nước',
    description: 'Uống đủ 1.5 - 2 lít nước mỗi ngày, ăn nhiều rau xanh và hạn chế đồ ngọt có gas.',
    hint: 'Tự đánh dấu vào bảng theo dõi uống nước 7 ngày.',
    xpReward: 25,
    coinReward: 10,
    difficulty: 'easy'
  },
  {
    id: 'fam_16',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '😴',
    title: 'Đi Ngủ Sớm Trước 10h30 Tối',
    description: 'Duy trì thói quen đi ngủ đúng giờ để đảm bảo giấc ngủ sâu và thức dậy tỉnh táo.',
    hint: 'Ghi nhật ký giờ ngủ và giờ thức dậy trong tuần.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_17',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🛒',
    title: 'Đi Chợ / Siêu Thị Giúp Bố Mẹ',
    description: 'Cầm danh sách đi mua thực phẩm đúng số lượng, biết so sánh giá và tính toán tiền thối.',
    hint: 'Chụp hóa đơn hoặc danh sách đồ đã mua.',
    xpReward: 35,
    coinReward: 20,
    difficulty: 'medium'
  },
  {
    id: 'fam_18',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '💌',
    title: 'Viết Thư Cảm Ơn Cha Mẹ',
    description: 'Viết một bức thư tay bày tỏ lòng biết ơn về sự hy sinh và chăm sóc của cha mẹ.',
    hint: 'Gửi bức thư tận tay cha mẹ và ghi lại khoảnh khắc ấm áp.',
    xpReward: 45,
    coinReward: 25,
    difficulty: 'hard'
  },
  {
    id: 'fam_19',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '🚦',
    title: 'Tuân Thủ An Toàn Giao Thông Tuyệt Đối',
    description: 'Đội mũ bảo hiểm đúng quy cách khi ngồi sau xe máy và quan sát kỹ khi qua đường.',
    hint: 'Ghi lại lời cam kết tham gia giao thông an toàn.',
    xpReward: 30,
    coinReward: 15,
    difficulty: 'easy'
  },
  {
    id: 'fam_20',
    category: 'family_lifeskills',
    categoryName: 'Gia Đình & Kỹ Năng Sống',
    categoryIcon: '👑',
    title: 'Người Con Hiếu Thảo & Độc Lập',
    description: 'Tự giác hoàn thành công việc cá nhân và giúp đỡ gia đình suốt tuần mà không cần nhắc nhở.',
    hint: 'Được cha mẹ ký xác nhận lời khen ngợi vào sổ rèn luyện.',
    xpReward: 50,
    coinReward: 35,
    difficulty: 'hard'
  }
];
